version: '3.8'

services:
  backend:
    build: ./backend              
    container_name: backend
    ports:
      - "5001:5000"              
    depends_on:
      - mongodb                   
    

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"             
    

  frontend:
    build: ./frontend              
    container_name: frontend
    ports:
      - "3000:3000"               
    depends_on:
      - backend                   

